name: Feature request
description: Propose a contract- and trace-auditable feature
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What regime/audit problem does this solve?
    validations:
      required: true
  - type: textarea
    id: contract
    attributes:
      label: Contract impact
      description: Which schemas/docs/fixtures would change or be added?
    validations:
      required: true
